apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: nginx-ingress-letsencrypt
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: fadelfirmansyah97@gmail.com
    privateKeySecretRef:
      name: nginx-ingress-letsencrypt
    solvers:
      - http01:
          ingress:
            class: nginx